name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --prefix Frontend

      - name: Build React app
        run: |
          export CI=false
          npm run build --prefix Frontend

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_THE_DIGITAL_TWIN_APP_3E2B1 }}
          channelId: live
          projectId: the-digital-twin-app-3e2b1
